import type { Product, OrderTrackingResponse } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  // ── Premium Services ──────────────────────────────────────────────────────
  {
    id: 'p001',
    name: 'Gazette Notification (Name/DOB Correction)',
    nameHi: 'राजपत्र अधिसूचना (नाम/जन्म तिथि सुधार)',
    price: 1500,
    category: 'Premium Services',
    emoji: '📰',
    badge: 'Official',
    description: 'Official legal correction via Govt Gazette for name or date of birth.',
    descriptionHi: 'सरकारी राजपत्र के माध्यम से नाम या जन्म तिथि का आधिकारिक कानूनी सुधार।',
    turnaround: '7–10 working days',
    turnaroundHi: '7–10 कार्य दिवस',
    documents: [
      'Aadhaar Card (original + photocopy)',
      'Birth Certificate or School Leaving Certificate',
      'Affidavit on ₹50 stamp paper',
      'Proof of current name (if name correction)',
      'Passport-size photograph (2 copies)',
    ],
    documentsHi: [
      'आधार कार्ड (मूल + फोटोकॉपी)',
      'जन्म प्रमाण पत्र या स्कूल छोड़ने का प्रमाण पत्र',
      '₹50 स्टाम्प पेपर पर शपथ पत्र',
      'वर्तमान नाम का प्रमाण (नाम सुधार के लिए)',
      'पासपोर्ट आकार की फोटो (2 प्रतियाँ)',
    ],
  },
  {
    id: 'p002',
    name: 'Business Project Report',
    nameHi: 'व्यवसाय परियोजना रिपोर्ट',
    price: 2000,
    originalPrice: 2500,
    category: 'Premium Services',
    emoji: '📊',
    badge: 'Popular',
    description: 'Professional project reports for bank loans and government subsidies.',
    descriptionHi: 'बैंक ऋण और सरकारी सब्सिडी के लिए पेशेवर परियोजना रिपोर्ट।',
    turnaround: '3–5 working days',
    turnaroundHi: '3–5 कार्य दिवस',
    documents: [
      'Business idea / type of business',
      'Aadhaar Card & PAN Card',
      'Bank account details',
      'Estimated investment amount',
      'Land/shop ownership or rent agreement',
    ],
    documentsHi: [
      'व्यवसाय का विचार / प्रकार',
      'आधार कार्ड और पैन कार्ड',
      'बैंक खाता विवरण',
      'अनुमानित निवेश राशि',
      'जमीन/दुकान स्वामित्व या किराया समझौता',
    ],
  },
  {
    id: 'p003',
    name: 'FSSAI Food License',
    nameHi: 'FSSAI खाद्य लाइसेंस',
    price: 1200,
    category: 'Premium Services',
    emoji: '🍽️',
    badge: 'New',
    description: 'Registration and license for food businesses under FSSAI regulations.',
    descriptionHi: 'FSSAI नियमों के तहत खाद्य व्यवसायों के लिए पंजीकरण और लाइसेंस।',
    turnaround: '10–15 working days',
    turnaroundHi: '10–15 कार्य दिवस',
    documents: [
      'Aadhaar Card & PAN Card',
      'Passport-size photographs (2)',
      'Proof of business address',
      'Bank account statement',
      'Nature of food business description',
    ],
    documentsHi: [
      'आधार कार्ड और पैन कार्ड',
      'पासपोर्ट आकार की फोटो (2)',
      'व्यवसाय पते का प्रमाण',
      'बैंक खाता विवरण',
      'खाद्य व्यवसाय का विवरण',
    ],
  },
  {
    id: 'p004',
    name: 'Passport Application Assistance',
    nameHi: 'पासपोर्ट आवेदन सहायता',
    price: 800,
    category: 'Premium Services',
    emoji: '🛂',
    description: 'End-to-end help for fresh passport and renewal applications.',
    descriptionHi: 'नए पासपोर्ट और नवीनीकरण के लिए पूर्ण सहायता।',
    turnaround: '2–3 working days (filing)',
    turnaroundHi: '2–3 कार्य दिवस (फाइलिंग)',
    documents: [
      'Aadhaar Card',
      'Birth Certificate',
      'Class 10 Certificate (as DOB proof)',
      'Existing passport (for renewal)',
      'Police Verification documents',
    ],
    documentsHi: [
      'आधार कार्ड',
      'जन्म प्रमाण पत्र',
      'कक्षा 10 का प्रमाण पत्र (जन्म तिथि प्रमाण के रूप में)',
      'मौजूदा पासपोर्ट (नवीनीकरण के लिए)',
      'पुलिस सत्यापन दस्तावेज',
    ],
  },

  // ── Govt Certificates ────────────────────────────────────────────────────
  {
    id: 'p005',
    name: 'PAN Card (New / Correction)',
    nameHi: 'पैन कार्ड (नया / सुधार)',
    price: 150,
    category: 'Govt Certificates',
    emoji: '🪪',
    badge: 'Fast',
    description: 'Fast PAN card processing — new application or data correction.',
    descriptionHi: 'नया आवेदन या डेटा सुधार — तेज़ पैन कार्ड प्रक्रिया।',
    turnaround: '1–2 working days',
    turnaroundHi: '1–2 कार्य दिवस',
    documents: [
      'Aadhaar Card',
      'Passport-size photograph',
      'Mobile number linked to Aadhaar',
      'Email address',
    ],
    documentsHi: [
      'आधार कार्ड',
      'पासपोर्ट आकार की फोटो',
      'आधार से जुड़ा मोबाइल नंबर',
      'ईमेल पता',
    ],
  },
  {
    id: 'p006',
    name: 'Income, Caste & Domicile Certificates',
    nameHi: 'आय, जाति और मूल निवास प्रमाण पत्र',
    price: 100,
    category: 'Govt Certificates',
    emoji: '📜',
    badge: 'Popular',
    description: 'Official state government certificates for income, caste and domicile.',
    descriptionHi: 'आय, जाति और मूल निवास के लिए राज्य सरकार के प्रमाण पत्र।',
    turnaround: '3–5 working days',
    turnaroundHi: '3–5 कार्य दिवस',
    documents: [
      'Aadhaar Card',
      'Ration Card / BPL Card',
      'Birth Certificate or Class 10 Marksheet',
      'Caste proof (for caste certificate)',
      'Residence proof (for domicile)',
    ],
    documentsHi: [
      'आधार कार्ड',
      'राशन कार्ड / बीपीएल कार्ड',
      'जन्म प्रमाण पत्र या कक्षा 10 की मार्कशीट',
      'जाति प्रमाण (जाति प्रमाण पत्र के लिए)',
      'निवास प्रमाण (मूल निवास के लिए)',
    ],
  },
  {
    id: 'p007',
    name: 'Aadhaar Update / Correction',
    nameHi: 'आधार अपडेट / सुधार',
    price: 50,
    category: 'Govt Certificates',
    emoji: '🔵',
    description: 'Name, address, DOB and mobile update on Aadhaar card.',
    descriptionHi: 'आधार कार्ड पर नाम, पता, जन्म तिथि और मोबाइल अपडेट।',
    turnaround: '5–7 working days',
    turnaroundHi: '5–7 कार्य दिवस',
    documents: [
      'Existing Aadhaar Card',
      'Proof of update (address/DOB/name proof)',
      'Mobile number (for OTP)',
    ],
    documentsHi: [
      'मौजूदा आधार कार्ड',
      'अपडेट का प्रमाण (पता/जन्म तिथि/नाम प्रमाण)',
      'मोबाइल नंबर (OTP के लिए)',
    ],
  },
  {
    id: 'p008',
    name: 'Birth / Death Certificate',
    nameHi: 'जन्म / मृत्यु प्रमाण पत्र',
    price: 80,
    category: 'Govt Certificates',
    emoji: '📋',
    description: 'Official birth and death certificates from municipal/panchayat records.',
    descriptionHi: 'नगर पालिका/पंचायत रिकॉर्ड से आधिकारिक जन्म और मृत्यु प्रमाण पत्र।',
    turnaround: '2–4 working days',
    turnaroundHi: '2–4 कार्य दिवस',
    documents: [
      'Hospital discharge slip or ANM record',
      'Parent\'s Aadhaar Card (for birth)',
      'Panchayat head letter',
      'Application form',
    ],
    documentsHi: [
      'अस्पताल डिस्चार्ज पर्ची या ANM रिकॉर्ड',
      'माता-पिता का आधार कार्ड (जन्म के लिए)',
      'पंचायत प्रमुख पत्र',
      'आवेदन पत्र',
    ],
  },
  {
    id: 'p009',
    name: 'PM-KISAN Registration & Status',
    nameHi: 'पीएम-किसान पंजीकरण और स्थिति',
    price: 50,
    category: 'Govt Certificates',
    emoji: '🌾',
    badge: 'Govt',
    description: 'Register for PM-KISAN scheme and check ₹6000/year instalment status.',
    descriptionHi: 'पीएम-किसान योजना के लिए पंजीकरण और ₹6000/वर्ष किस्त की स्थिति।',
    turnaround: '1 working day',
    turnaroundHi: '1 कार्य दिवस',
    documents: [
      'Aadhaar Card',
      'Bank Passbook (account number & IFSC)',
      'Land record / Khasra Khatauni',
      'Mobile number',
    ],
    documentsHi: [
      'आधार कार्ड',
      'बैंक पासबुक (खाता संख्या और IFSC)',
      'भूमि रिकॉर्ड / खसरा खतौनी',
      'मोबाइल नंबर',
    ],
  },
  {
    id: 'p010',
    name: 'E-Shram Card',
    nameHi: 'ई-श्रम कार्ड',
    price: 0,
    category: 'Govt Certificates',
    emoji: '👷',
    badge: 'Free',
    description: 'National database registration for unorganized sector workers.',
    descriptionHi: 'असंगठित क्षेत्र के श्रमिकों के लिए राष्ट्रीय डेटाबेस पंजीकरण।',
    turnaround: 'Same day',
    turnaroundHi: 'उसी दिन',
    documents: [
      'Aadhaar Card',
      'Bank account details',
      'Mobile number linked to Aadhaar',
      'Occupation details',
    ],
    documentsHi: [
      'आधार कार्ड',
      'बैंक खाता विवरण',
      'आधार से जुड़ा मोबाइल नंबर',
      'व्यवसाय विवरण',
    ],
  },
  {
    id: 'p011',
    name: 'Driving License (New / Renewal)',
    nameHi: 'ड्राइविंग लाइसेंस (नया / नवीनीकरण)',
    price: 300,
    category: 'Govt Certificates',
    emoji: '🚗',
    description: 'Learner\'s license, permanent DL, and renewal application assistance.',
    descriptionHi: 'लर्नर लाइसेंस, स्थायी DL और नवीनीकरण आवेदन सहायता।',
    turnaround: '3–5 working days',
    turnaroundHi: '3–5 कार्य दिवस',
    documents: [
      'Aadhaar Card',
      'Age proof (Class 10 certificate)',
      'Medical certificate (Form 1A)',
      'Passport-size photographs (3)',
      'Existing DL (for renewal)',
    ],
    documentsHi: [
      'आधार कार्ड',
      'आयु प्रमाण (कक्षा 10 का प्रमाण पत्र)',
      'चिकित्सा प्रमाण पत्र (फॉर्म 1A)',
      'पासपोर्ट आकार की फोटो (3)',
      'मौजूदा DL (नवीनीकरण के लिए)',
    ],
  },
  {
    id: 'p012',
    name: 'Ayushman Bharat Card',
    nameHi: 'आयुष्मान भारत कार्ड',
    price: 0,
    category: 'Govt Certificates',
    emoji: '🏥',
    badge: 'Free',
    description: 'PM-JAY health card giving ₹5 lakh health cover to eligible families.',
    descriptionHi: 'पात्र परिवारों को ₹5 लाख स्वास्थ्य कवर देने वाला पीएम-जेएवाई स्वास्थ्य कार्ड।',
    turnaround: 'Same day',
    turnaroundHi: 'उसी दिन',
    documents: [
      'Aadhaar Card',
      'Ration Card',
      'Mobile number',
    ],
    documentsHi: [
      'आधार कार्ड',
      'राशन कार्ड',
      'मोबाइल नंबर',
    ],
  },

  // ── Banking & Finance ────────────────────────────────────────────────────
  {
    id: 'p013',
    name: 'HDFC Bank BC Services',
    nameHi: 'HDFC बैंक BC सेवाएं',
    price: 0,
    category: 'Banking & Finance',
    emoji: '🏦',
    badge: 'Free',
    description: 'Account opening, cash withdrawal, deposits and mini statement.',
    descriptionHi: 'खाता खोलना, नकद निकासी, जमा और मिनी स्टेटमेंट।',
    turnaround: 'Instant',
    turnaroundHi: 'तुरंत',
    documents: [
      'Aadhaar Card',
      'PAN Card',
      'Passport-size photograph',
      'Mobile number',
    ],
    documentsHi: [
      'आधार कार्ड',
      'पैन कार्ड',
      'पासपोर्ट आकार की फोटो',
      'मोबाइल नंबर',
    ],
  },
  {
    id: 'p014',
    name: 'GST Registration',
    nameHi: 'GST पंजीकरण',
    price: 500,
    category: 'Banking & Finance',
    emoji: '🧾',
    description: 'GST number registration for businesses above ₹20 lakh turnover.',
    descriptionHi: '₹20 लाख से अधिक टर्नओवर वाले व्यवसायों के लिए GST नंबर पंजीकरण।',
    turnaround: '3–7 working days',
    turnaroundHi: '3–7 कार्य दिवस',
    documents: [
      'PAN Card of business',
      'Aadhaar Card of proprietor',
      'Business address proof',
      'Bank account details',
      'Digital signature (for companies)',
    ],
    documentsHi: [
      'व्यवसाय का पैन कार्ड',
      'स्वामी का आधार कार्ड',
      'व्यवसाय पते का प्रमाण',
      'बैंक खाता विवरण',
      'डिजिटल हस्ताक्षर (कंपनियों के लिए)',
    ],
  },
  {
    id: 'p015',
    name: 'ITR Filing (Income Tax Return)',
    nameHi: 'ITR दाखिल करना (आयकर रिटर्न)',
    price: 300,
    category: 'Banking & Finance',
    emoji: '📑',
    badge: 'Popular',
    description: 'Income tax return filing for individuals and small businesses.',
    descriptionHi: 'व्यक्तियों और छोटे व्यवसायों के लिए आयकर रिटर्न दाखिल करना।',
    turnaround: '1–2 working days',
    turnaroundHi: '1–2 कार्य दिवस',
    documents: [
      'PAN Card',
      'Aadhaar Card',
      'Form 16 (from employer)',
      'Bank statement / passbook',
      'Investment proof (if any)',
    ],
    documentsHi: [
      'पैन कार्ड',
      'आधार कार्ड',
      'फॉर्म 16 (नियोक्ता से)',
      'बैंक स्टेटमेंट / पासबुक',
      'निवेश प्रमाण (यदि कोई हो)',
    ],
  },

  // ── Education & Exams ────────────────────────────────────────────────────
  {
    id: 'p016',
    name: 'Competitive Exam Form Filling',
    nameHi: 'प्रतियोगी परीक्षा फॉर्म भरना',
    price: 100,
    category: 'Education & Exams',
    emoji: '📝',
    badge: 'Popular',
    description: 'RPSC, SSC, Railway (RRB), REET and other exam application forms.',
    descriptionHi: 'RPSC, SSC, रेलवे (RRB), REET और अन्य परीक्षा आवेदन पत्र।',
    turnaround: 'Same day',
    turnaroundHi: 'उसी दिन',
    documents: [
      'Aadhaar Card',
      'Educational certificates (10th, 12th, Graduation)',
      'Passport-size photograph (latest)',
      'Signature (scanned)',
      'Category certificate (SC/ST/OBC) if applicable',
    ],
    documentsHi: [
      'आधार कार्ड',
      'शैक्षिक प्रमाण पत्र (10वीं, 12वीं, स्नातक)',
      'पासपोर्ट आकार की फोटो (नवीनतम)',
      'हस्ताक्षर (स्कैन किया हुआ)',
      'श्रेणी प्रमाण पत्र (SC/ST/OBC) यदि लागू हो',
    ],
  },
  {
    id: 'p017',
    name: 'Scholarship Application (State & Central)',
    nameHi: 'छात्रवृत्ति आवेदन (राज्य और केंद्रीय)',
    price: 50,
    category: 'Education & Exams',
    emoji: '🎓',
    description: 'Apply for NSP, state board and minority scholarships online.',
    descriptionHi: 'NSP, राज्य बोर्ड और अल्पसंख्यक छात्रवृत्ति के लिए ऑनलाइन आवेदन।',
    turnaround: '1 working day',
    turnaroundHi: '1 कार्य दिवस',
    documents: [
      'Aadhaar Card',
      'Bank account (in student\'s name)',
      'Income certificate of parent',
      'Caste certificate (if applicable)',
      'Previous year marksheet',
      'Bonafide / school/college enrollment proof',
    ],
    documentsHi: [
      'आधार कार्ड',
      'बैंक खाता (छात्र के नाम पर)',
      'माता-पिता का आय प्रमाण पत्र',
      'जाति प्रमाण पत्र (यदि लागू हो)',
      'पिछले वर्ष की मार्कशीट',
      'बोनाफाइड / स्कूल/कॉलेज नामांकन प्रमाण',
    ],
  },

  // ── Insurance ────────────────────────────────────────────────────────────
  {
    id: 'p018',
    name: 'Vehicle & Health Insurance',
    nameHi: 'वाहन और स्वास्थ्य बीमा',
    price: 500,
    category: 'Insurance',
    emoji: '🛡️',
    badge: 'Popular',
    description: 'Policy issuance and premium renewal for vehicle and health insurance.',
    descriptionHi: 'वाहन और स्वास्थ्य बीमा के लिए पॉलिसी जारी करना और प्रीमियम नवीनीकरण।',
    turnaround: 'Same day',
    turnaroundHi: 'उसी दिन',
    documents: [
      'Aadhaar Card',
      'Vehicle RC (for vehicle insurance)',
      'Previous policy (for renewal)',
      'PAN Card',
    ],
    documentsHi: [
      'आधार कार्ड',
      'वाहन RC (वाहन बीमा के लिए)',
      'पिछली पॉलिसी (नवीनीकरण के लिए)',
      'पैन कार्ड',
    ],
  },
  {
    id: 'p019',
    name: 'LIC / Life Insurance Policy',
    nameHi: 'LIC / जीवन बीमा पॉलिसी',
    price: 500,
    category: 'Insurance',
    emoji: '💼',
    description: 'New LIC policy enrollment and existing policy premium payment.',
    descriptionHi: 'नई LIC पॉलिसी नामांकन और मौजूदा पॉलिसी प्रीमियम भुगतान।',
    turnaround: '1–2 working days',
    turnaroundHi: '1–2 कार्य दिवस',
    documents: [
      'Aadhaar Card',
      'PAN Card',
      'Passport-size photographs (2)',
      'Bank account details',
      'Nominee Aadhaar Card',
    ],
    documentsHi: [
      'आधार कार्ड',
      'पैन कार्ड',
      'पासपोर्ट आकार की फोटो (2)',
      'बैंक खाता विवरण',
      'नामांकित व्यक्ति का आधार कार्ड',
    ],
  },
  {
    id: 'p020',
    name: 'PM Awas Yojana Application',
    nameHi: 'पीएम आवास योजना आवेदन',
    price: 0,
    category: 'Govt Certificates',
    emoji: '🏠',
    badge: 'Free',
    description: 'Apply for Pradhan Mantri Awas Yojana (Gramin & Shahari) housing scheme.',
    descriptionHi: 'प्रधानमंत्री आवास योजना (ग्रामीण और शहरी) आवास योजना के लिए आवेदन।',
    turnaround: '2–3 working days',
    turnaroundHi: '2–3 कार्य दिवस',
    documents: [
      'Aadhaar Card',
      'Ration Card',
      'Bank account details',
      'Income certificate',
      'Land / plot ownership documents',
    ],
    documentsHi: [
      'आधार कार्ड',
      'राशन कार्ड',
      'बैंक खाता विवरण',
      'आय प्रमाण पत्र',
      'भूमि / प्लॉट स्वामित्व दस्तावेज',
    ],
  },
  {
    id: 's_automation_single_monthly',
    name: 'Land Records Automation Suite (Single Device - Monthly)',
    nameHi: 'ऑटोमेशन सॉफ्टवेयर (सिंगल डिवाइस - मासिक)',
    price: 50,
    category: 'Premium Services',
    emoji: '💻',
    badge: 'Popular',
    description: 'Python automation software for single machine locked key (30 Days).',
    descriptionHi: 'जमाबंदी नकल, नक्शा ट्रेस ऑटोमेशन सॉफ्टवेयर, सिंगल पीसी लॉक की (30 दिन)।',
    turnaround: 'Instant Key Generation',
    turnaroundHi: 'तुरंत की (Key) एक्टिवेशन',
    documents: [
      'Windows 10/11 64-bit PC',
      'Machine ID (generated by software)',
    ],
    documentsHi: [
      'विंडोज 10/11 64-बिट कंप्यूटर',
      'मशीन आईडी (सॉफ्टवेयर द्वारा दी गई)',
    ],
  },
  {
    id: 's_automation_single_yearly',
    name: 'Land Records Automation Suite (Single Device - Yearly)',
    nameHi: 'ऑटोमेशन सॉफ्टवेयर (सिंगल डिवाइस - वार्षिक)',
    price: 500,
    category: 'Premium Services',
    emoji: '👑',
    badge: 'Best Value',
    description: 'Python automation software for single machine locked key (12 Months).',
    descriptionHi: 'जमाबंदी नकल, नक्शा ट्रेस ऑटोमेशन सॉफ्टवेयर, सिंगल पीसी लॉक की (1 साल)।',
    turnaround: 'Instant Key Generation',
    turnaroundHi: 'तुरंत की (Key) एक्टिवेशन',
    documents: [
      'Windows 10/11 64-bit PC',
      'Machine ID (generated by software)',
    ],
    documentsHi: [
      'विंडोज 10/11 64-बिट कंप्यूटर',
      'मशीन आईडी (सॉफ्टवेयर द्वारा दी गई)',
    ],
  },
  {
    id: 's_automation_multi_monthly',
    name: 'Land Records Automation Suite (Multiple Devices - Monthly)',
    nameHi: 'ऑटोमेशन सॉफ्टवेयर (मल्टी डिवाइस - मासिक)',
    price: 150,
    category: 'Premium Services',
    emoji: '💻',
    badge: 'Multi-PC',
    description: 'Python automation software for up to 3 machines locked key (30 Days).',
    descriptionHi: 'ऑटोमेशन सॉफ्टवेयर, 3 पीसी तक लॉक की (30 दिन)।',
    turnaround: 'Instant Key Generation',
    turnaroundHi: 'तुरंत की (Key) एक्टिवेशन',
    documents: [
      'Windows 10/11 64-bit PC',
      'Machine ID (generated by software)',
    ],
    documentsHi: [
      'विंडोज 10/11 64-बिट कंप्यूटर',
      'मशीन आईडी (सॉफ्टवेयर द्वारा दी गई)',
    ],
  },
  {
    id: 's_automation_multi_yearly',
    name: 'Land Records Automation Suite (Multiple Devices - Yearly)',
    nameHi: 'ऑटोमेशन सॉफ्टवेयर (मल्टी डिवाइस - वार्षिक)',
    price: 1500,
    originalPrice: 1800,
    category: 'Premium Services',
    emoji: '👑',
    badge: 'Multi-PC Save',
    description: 'Python automation software for up to 3 machines locked key (12 Months).',
    descriptionHi: 'ऑटोमेशन सॉफ्टवेयर, 3 पीसी तक लॉक की (1 साल)।',
    turnaround: 'Instant Key Generation',
    turnaroundHi: 'तुरंत की (Key) एक्टिवेशन',
    documents: [
      'Windows 10/11 64-bit PC',
      'Machine ID (generated by software)',
    ],
    documentsHi: [
      'विंडोज 10/11 64-बिट कंप्यूटर',
      'मशीन आईडी (सॉफ्टवेयर द्वारा दी गई)',
    ],
  },
];

export const MOCK_ORDER_TRACKING: OrderTrackingResponse = {
  order_ref: 'CSC-2024-001234',
  status: 'processing',
  customer_name: 'Ramesh Kumar',
  service_name: 'PAN Card (New / Correction)',
  service_nameHi: 'पैन कार्ड (नया / सुधार)',
  total: 150,
  delivery_type: 'digital',
  created_at: new Date(Date.now() - 86400000).toISOString(),
  updated_at: new Date().toISOString(),
  payment_link: 'https://rzp.io/l/example',
  completion_info: undefined,
};
